import Head from 'next/head'
import FlexContainer from '@/containers/FlexContainer'
import { useRouter } from 'next/router'
import EBOOK_DATA from '@/data/eBookData'
import EbookList from "./../components/EbookList"
import CenterContainer from '@/containers/CenterContainer'

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CenterContainer>

        {/* <EbookList /> */}
        <h1 style={{ textAlign: "center", margin: "1rem" }}>Hier entsteht eine Demonstration für das Projekt "Si-Sa"</h1>
      </CenterContainer>
    </>
  )
}
